FROM python:3.12-slim-bookworm as base
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ADD . /app
WORKDIR /app

FROM BASE as production
# Install the application dependencies.
RUN uv sync --frozen --no-cache

# Run the application.
CMD ["/app/.venv/bin/fastapi", "run", "app/main.py", "--port", "80", "--host", "0.0.0.0"]


FROM BASE as development
RUN uv sync --locked
CMD ["uv", "run", "fastapi", "dev"]
