FROM python:3.12-slim-bookworm AS base
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ADD . /app
WORKDIR /app

FROM base AS prod
# Install the application dependencies.
RUN uv sync --frozen --no-cache

# Run the application.
CMD ["/app/.venv/bin/fastapi", "run", "/app/app/main.py", "--port", "80", "--host", "0.0.0.0"]


FROM base AS dev
RUN uv sync --locked
CMD ["uv", "run", "fastapi", "dev", "--host", "0.0.0.0", "/app/app/main.py"]
